"number of data points"                = 46
"number of variables"                  = 3
"chi-square"                           =  6.92508e+01
"reduced-chi-square"                   =  1.61048e+00
"chi-squared test"                     =  6.77770e-03
"Kolmogorov-Smirnov test"              =  7.63973e-01
"Akaike Information Criterion (AIC)"   =  7.52508e+01
"Bayesian Information Criterion (BIC)" =  8.07367e+01
