ARG NODE_IMAGE=docker.io/library/node:24-trixie-slim@sha256:a747ad80c8a161b650d79a6da9c422005b91148b18b8d2c669eb5a0b7c07e600
ARG CADDY_IMAGE=docker.io/library/caddy:2-alpine@sha256:98eb57d882ccd5213d1688764db10c1ca2c58a1ca3a6717a3411ad798f7a423a

FROM ${NODE_IMAGE} AS builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM ${CADDY_IMAGE}
COPY containers/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /app/dist /srv/dist

EXPOSE 8080
