"number of data points"                = 46
"number of variables"                  = 3
"chi-square"                           =  1.94779e+02
"reduced-chi-square"                   =  4.52974e+00
"chi-squared test"                     =  0.00000e+00
"Kolmogorov-Smirnov test"              =  8.55606e-03
"Akaike Information Criterion (AIC)"   =  2.00779e+02
"Bayesian Information Criterion (BIC)" =  2.06265e+02
