import os
import json
import io
import matplotlib
matplotlib.use('Agg') # Necessary for headless server environments
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np

def generate_cest_pdf_report(analysis_dir: str, analysis_name: str, analysis_type: str = "CEST") -> io.BytesIO:
    """
    Generate a multi-page PDF report for a CEST or CPMG analysis.
    """
    # Dynamically re-parse to ensure report uses latest format
    try:
        from .cest_tasks import _parse_chemex_output
        parsed = _parse_chemex_output(analysis_dir)
        if parsed and parsed.get("residues"):
            from datetime import datetime
            with open(os.path.join(analysis_dir, "results.json"), "w") as f:
                json.dump({
                    "analysis_uuid": os.path.basename(analysis_dir),
                    "timestamp": datetime.now().isoformat(),
                    "fit_mode": parsed.get("fit_mode", "global"),
                    **parsed
                }, f, indent=2)
    except Exception:
        pass

    results_path = os.path.join(analysis_dir, "results.json")
    if not os.path.exists(results_path):
        raise FileNotFoundError(f"Results file not found at {results_path}")
    
    with open(results_path, "r") as f:
        results = json.load(f)
    
    config_path = os.path.join(analysis_dir, "cpmg_config.json") if os.path.exists(os.path.join(analysis_dir, "cpmg_config.json")) else os.path.join(analysis_dir, "config.json")
    residue_mapping = {}
    if os.path.exists(config_path):
        try:
            with open(config_path, "r") as cf:
                config = json.load(cf)
                residue_mapping = config.get("residue_mapping", {})
        except Exception:
            pass

    buf = io.BytesIO()
    
    # Use a clean style
    plt.style.use('bmh')
    
    with PdfPages(buf) as pdf:
        # --- Page 1: Summary ---
        fig_summary = plt.figure(figsize=(8.5, 11))
        # ... (rest of title page same as before)
        plt.clf()
        plt.axis('off')
        
        plt.text(0.5, 0.95, f"{analysis_type.upper()} Analysis Report: {analysis_name}", 
                 fontsize=18, fontweight='bold', ha='center')
        plt.text(0.5, 0.92, f"Analysis UUID: {results.get('analysis_uuid', 'N/A')}", 
                 fontsize=10, color='gray', ha='center')
        
        # Global Table
        g = results.get("global", {})
        global_data = [
            ["Parameter", "Value"],
            ["Exchange Rate (k_ex)", f"{g.get('kex_ab', 0):.2f} s⁻¹"],
            ["Excited Pop. (p_b)", f"{g.get('pb', 0)*100:.2f} %"],
            ["Overall Chi-Square", f"{g.get('chi2', 0):.2f}"],
            ["Reduced Chi-Square", f"{g.get('chi2_red', 0):.2f}"],
            ["Correlation Time (tau_c)", f"{g.get('tauc_a', 0)} ns"]
        ]
        
        table = plt.table(cellText=global_data, colWidths=[0.4, 0.4], 
                          loc='center', cellLoc='center', bbox=[0.1, 0.6, 0.8, 0.25])
        table.auto_set_font_size(False)
        table.set_fontsize(12)
        
        # Add a footer
        plt.text(0.5, 0.05, "Generated by resoFlow", fontsize=8, color='gray', ha='center')
        
        pdf.savefig(fig_summary)
        plt.close(fig_summary)

        # --- Data Prep for Diagnostics ---
        residues = results.get("residues", {})
        import re
        def natural_sort_key(s):
            return [int(text) if text.isdigit() else text.lower() for text in re.split('([0-9]+)', s)]
        
        sorted_keys = sorted(residues.keys(), key=natural_sort_key)
        
        res_list = [residue_mapping.get(k, k) for k in sorted_keys]
        chi2_list = [residues[k].get("parameters", {}).get("chi2_red") for k in sorted_keys]
        r2a_list = [residues[k].get("parameters", {}).get("r2_a") for k in sorted_keys]
        r2b_list = [residues[k].get("parameters", {}).get("r2_b") for k in sorted_keys]
        pb_list = [residues[k].get("parameters", {}).get("pb") or g.get("pb") for k in sorted_keys]
        kex_list = [residues[k].get("parameters", {}).get("kex_ab") or g.get("kex_ab") for k in sorted_keys]

        # --- Page 2: Diagnostic Plots (Chi2 and R2) ---
        fig_diag = plt.figure(figsize=(8.5, 11))
        
        # Reduced Chi2 Plot
        ax_chi2 = plt.subplot(2, 1, 1)
        valid_indices = [i for i, v in enumerate(chi2_list) if v is not None]
        if valid_indices:
            x_vals = [res_list[i] for i in valid_indices]
            y_vals = [chi2_list[i] for i in valid_indices]
            ax_chi2.scatter(x_vals, y_vals, color='#1f77b4', s=60, alpha=0.7, edgecolors='w', linewidth=0.5)
        ax_chi2.set_title("Reduced Chi-Square vs Residue", fontsize=14, fontweight='bold')
        ax_chi2.set_ylabel("Reduced χ²")
        plt.setp(ax_chi2.get_xticklabels(), rotation=45, ha='right', fontsize=8)

        # R2 Values Plot
        ax_r2 = plt.subplot(2, 1, 2)
        v_a = [i for i, v in enumerate(r2a_list) if v is not None]
        if v_a:
            ax_r2.scatter([res_list[i] for i in v_a], [r2a_list[i] for i in v_a], 
                          color='#1f77b4', label='R2A (Ground)', s=60, alpha=0.8, edgecolors='w')
        v_b = [i for i, v in enumerate(r2b_list) if v is not None]
        if v_b:
            ax_r2.scatter([res_list[i] for i in v_b], [r2b_list[i] for i in v_b], 
                          color='#d62728', label='R2B (Excited)', s=60, marker='d', alpha=0.8, edgecolors='#d62728', facecolors='none', linewidth=1)
        
        ax_r2.set_title("R2 Values vs Residue", fontsize=14, fontweight='bold')
        ax_r2.set_ylabel("R₂ (s⁻¹)")
        ax_r2.legend()
        plt.setp(ax_r2.get_xticklabels(), rotation=45, ha='right', fontsize=8)

        plt.tight_layout(pad=4.0)
        pdf.savefig(fig_diag)
        plt.close(fig_diag)

        # --- Page 3: Kinetic Correlation ---
        fig_kin = plt.figure(figsize=(8.5, 8.5))
        ax_kin = fig_kin.add_subplot(1, 1, 1)
        
        # Filter consistently to ensure equal lengths
        kin_data = []
        for i, res in enumerate(sorted_keys):
            pb = pb_list[i]
            kex = kex_list[i]
            if pb is not None and kex is not None:
                kin_data.append({
                    "res": residue_mapping.get(res, res),
                    "pb": pb * 100,
                    "kex": kex
                })

        if kin_data:
            x_pb = [d["pb"] for d in kin_data]
            y_kex = [d["kex"] for d in kin_data]
            marker_labels = [d["res"] for d in kin_data]
            
            ax_kin.scatter(x_pb, y_kex, color='#1f77b4', s=100, alpha=0.6, edgecolors='w')
            for i, txt in enumerate(marker_labels):
                ax_kin.annotate(txt, (x_pb[i], y_kex[i]), fontsize=8, alpha=0.7, xytext=(5, 5), textcoords='offset points')
        
        ax_kin.set_title("Kinetic Correlation (k_ex vs p_b)", fontsize=14, fontweight='bold')
        ax_kin.set_xlabel("Excited Population p_b (%)")
        ax_kin.set_ylabel("Exchange Rate k_ex (s⁻¹)")
        
        plt.tight_layout(pad=4.0)
        pdf.savefig(fig_kin)
        plt.close(fig_kin)

        # --- Grid Search Summary Page (if Grid exists in any step) ---
        grid_step_name = None
        steps_dict = results.get("steps", {})
        for sname, sdata in steps_dict.items():
            if sdata.get("has_grid"):
                grid_step_name = sname
                break

        try:
            from .chemex_output.grid_parser import get_grid_data_for_group, compute_1d_profiles, compute_2d_surface, compute_grid_minimum
            from pathlib import Path
            a_path = Path(analysis_dir)
            candidate_gdirs = [
                a_path / grid_step_name / "Grid" if grid_step_name else None,
                a_path / "Output" / grid_step_name / "Grid" if grid_step_name else None,
                a_path / "STEP1" / "Grid",
                a_path / "Output" / "STEP1" / "Grid",
                a_path / "Grid",
                a_path / "Output" / "Grid",
            ]
            g_dir = next((d for d in candidate_gdirs if d and d.is_dir()), None)
            if g_dir:
                pnames, agg_data, _ = get_grid_data_for_group(g_dir, None, residue_mapping=residue_mapping)
                if len(pnames) >= 2:
                    surf = compute_2d_surface(pnames, agg_data, pnames[0], pnames[1])
                    profs = compute_1d_profiles(pnames, agg_data)
                    min_pt = compute_grid_minimum(pnames, agg_data)

                    fig_grid = plt.figure(figsize=(8.5, 11))
                    ax_2d = plt.subplot2grid((3, 2), (0, 0), colspan=2, rowspan=2)
                    X = np.array(surf["x"])
                    Y = np.array(surf["y"])
                    Z = np.array(surf["z_delta"])

                    cs = ax_2d.contourf(X, Y, Z, levels=20, cmap="viridis")
                    plt.colorbar(cs, ax=ax_2d, label=r"$\Delta \chi^2$")
                    ax_2d.set_title(f"Grid Search Surface: {surf['x_param']} vs {surf['y_param']}", fontsize=14, fontweight='bold')
                    ax_2d.set_xlabel(surf['x_param'])
                    ax_2d.set_ylabel(surf['y_param'])

                    if min_pt["coordinates"]:
                        mx = min_pt["coordinates"].get(surf['x_param'])
                        my = min_pt["coordinates"].get(surf['y_param'])
                        if mx is not None and my is not None:
                            ax_2d.scatter([mx], [my], color='red', marker='*', s=150, label='Grid Minimum', zorder=5)
                            ax_2d.legend(loc='upper right')

                    for p_i, prof in enumerate(profs[:2]):
                        ax_1d = plt.subplot2grid((3, 2), (2, p_i))
                        ax_1d.plot(prof["x"], prof["delta_chisqr"], marker='o', markersize=3, color='#1f77b4')
                        ax_1d.set_title(f"Profile: {prof['parameter']}", fontsize=11, fontweight='bold')
                        ax_1d.set_xlabel(prof['parameter'])
                        ax_1d.set_ylabel(r"$\Delta \chi^2$")

                    plt.tight_layout(pad=3.0)
                    pdf.savefig(fig_grid)
                    plt.close(fig_grid)
        except Exception:
            pass

        # --- Pages 4+: Residue Details ---
        sorted_res = sorted_keys
        
        for res_label in sorted_res:
            res_data = residues[res_label]
            params = res_data.get("parameters", {})
            experiments = res_data.get("experiments", [])
            
            if not experiments: continue
            
            fig = plt.figure(figsize=(8.5, 11))
            
            # Subplot for CEST Profile
            ax_plot = plt.subplot2grid((2, 1), (0, 0))
            
            color_palette = ['#1f77b4', '#9467bd', '#2ca02c', '#d62728', '#ff7f0e', '#17becf']
            
            for i, exp in enumerate(experiments):
                color = color_palette[i % len(color_palette)]
                label = exp.get("b1_label", f"Field {i}")
                
                # Experimental Points
                ep = exp.get("exp_points", {})
                if ep.get("x"):
                    ax_plot.errorbar(ep["x"], ep["y"], yerr=ep.get("y_err"), 
                                     fmt='o', color=color, markersize=4, label=label, alpha=0.6)
                
                # Fit Curve
                fc = exp.get("fit_curve", {})
                if fc.get("x"):
                    ax_plot.plot(fc["x"], fc["y"], '-', color=color, linewidth=2)
            
            display_label = residue_mapping.get(res_label, res_label)
            ax_plot.set_title(f"Residue: {display_label}", fontsize=14, fontweight='bold')
            if analysis_type.upper() == "CPMG":
                ax_plot.set_xlabel(r"$\nu_{\mathrm{CPMG}}$ (Hz)")
                ax_plot.set_ylabel(r"$R_{2,\mathrm{eff}}$ ($\mathrm{s}^{-1}$)")
            else:
                ax_plot.set_xlabel("Shift (ppm)")
                ax_plot.set_ylabel("I / I₀")
                ax_plot.invert_xaxis()
            ax_plot.legend(loc='lower center', bbox_to_anchor=(0.5, -0.2), ncol=3, fontsize=9)
            
            # Vertical lines for CS_A, CS_B (for CEST)
            if analysis_type.upper() != "CPMG":
                cs_a = params.get("cs_a")
                if cs_a:
                    ax_plot.axvline(cs_a, color='gray', linestyle='--', alpha=0.5)
                    ax_plot.text(cs_a, 1.02, 'A', transform=ax_plot.get_xaxis_transform(), 
                                 ha='center', fontsize=10, color='gray')
                
                cs_b = params.get("cs_b") or (cs_a + params.get("dw_ab", 0) if cs_a and params.get("dw_ab") is not None else None)
                if cs_b:
                    ax_plot.axvline(cs_b, color='red', linestyle='--', alpha=0.5)
                    ax_plot.text(cs_b, 1.02, 'B', transform=ax_plot.get_xaxis_transform(), 
                                 ha='center', fontsize=10, color='red')
            
            # Subplot for Parameters Table
            ax_table = plt.subplot2grid((2, 1), (1, 0))
            ax_table.axis('off')
            
            # Prepare parameter data
            p_data = [
                ["Parameter", "Value"],
                ["Chi-Square", f"{params.get('chi2', 0):.2f}"],
                ["Reduced Chi-Square", f"{params.get('chi2_red', 0):.2f}"],
                ["R1_A", f"{params.get('r1_a', '—')}"],
                ["R2_A", f"{params.get('r2_a', '—')}"],
                ["DW_AB", f"{params.get('dw_ab', 0):.3f} ppm"],
                ["CS_A", f"{params.get('cs_a', 0):.3f} ppm"],
                ["CS_B", f"{cs_b or '—'} ppm"]
            ]
            
            res_table = ax_table.table(cellText=p_data, colWidths=[0.3, 0.4], 
                                       loc='center', cellLoc='center', bbox=[0.15, 0.1, 0.7, 0.8])
            res_table.auto_set_font_size(False)
            res_table.set_fontsize(10)
            
            plt.tight_layout(rect=[0, 0.05, 1, 0.95])
            pdf.savefig(fig)
            plt.close(fig)
            
    buf.seek(0)
    return buf
