["DW_AB, NUC->15N"]
interval = "95% percentile"
sample_count = 0

["KEX_AB"]
interval = "95% percentile"
sample_count = 0

["PB"]
interval = "95% percentile"
sample_count = 0

["R2_A, NUC->15N, B0->500.0MHZ"]
interval = "95% percentile"
sample_count = 0

["R2_A, NUC->15N, B0->800.0MHZ"]
interval = "95% percentile"
sample_count = 0
