"number of data points"                = 46
"number of variables"                  = 3
"chi-square"                           =  4.12842e+01
"reduced-chi-square"                   =  9.60097e-01
"chi-squared test"                     =  5.45911e-01
"Kolmogorov-Smirnov test"              =  7.35393e-01
"Akaike Information Criterion (AIC)"   =  4.72842e+01
"Bayesian Information Criterion (BIC)" =  5.27701e+01
