"number of data points"                = 92
"number of variables"                  = 6
"chi-square"                           =  2.36063e+02
"reduced-chi-square"                   =  2.74492e+00
"chi-squared test"                     =  6.66134e-16
"Kolmogorov-Smirnov test"              =  1.57964e-01
"Akaike Information Criterion (AIC)"   =  2.48063e+02
"Bayesian Information Criterion (BIC)" =  2.63194e+02
