"number of data points"                = 46
"number of variables"                  = 5
"chi-square"                           =  2.18470e+02
"reduced-chi-square"                   =  5.32855e+00
"chi-squared test"                     =  0.00000e+00
"Kolmogorov-Smirnov test"              =  4.54936e-03
"Akaike Information Criterion (AIC)"   =  2.28470e+02
"Bayesian Information Criterion (BIC)" =  2.37614e+02
