"""baseline_schema

Revision ID: 37a19caa9d6c
Revises: 
Create Date: 2026-08-25 11:08:25.147851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a19caa9d6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('local_directory_path', sa.String(), nullable=True),
    sa.Column('protein_sequence', sa.String(), nullable=True),
    sa.Column('molecular_weight', sa.String(), nullable=True),
    sa.Column('spectra_path', sa.String(), nullable=True),
    sa.Column('experiments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_uuid'), ['project_uuid'], unique=True)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('use_height', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_path', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_analysis_uuid'), ['analysis_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_name'), ['name'], unique=False)

    op.create_table('spectra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spectrum_uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('experiment_type', sa.String(), nullable=True),
    sa.Column('peaklist_path', sa.String(), nullable=True),
    sa.Column('list_path', sa.String(), nullable=True),
    sa.Column('vclist_path', sa.String(), nullable=True),
    sa.Column('vdlist_path', sa.String(), nullable=True),
    sa.Column('f3list_path', sa.String(), nullable=True),
    sa.Column('delay', sa.Float(), nullable=True),
    sa.Column('t_relax', sa.Float(), nullable=True),
    sa.Column('b1', sa.Float(), nullable=True),
    sa.Column('hetnoe_mode', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_fitted', sa.Boolean(), nullable=True),
    sa.Column('results_json_path', sa.String(), nullable=True),
    sa.Column('peaktable_json_path', sa.String(), nullable=True),
    sa.Column('b0', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('carrier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spectra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spectra_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_spectra_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spectra_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_spectra_spectrum_uuid'), ['spectrum_uuid'], unique=True)

    op.create_table('analysis_spectra',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('spectrum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ),
    sa.PrimaryKeyConstraint('analysis_id', 'spectrum_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_uuid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_clusters', sa.Integer(), nullable=True),
    sa.Column('completed_clusters', sa.Integer(), nullable=True),
    sa.Column('processors', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('spectrum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_uuid'), ['job_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_uuid'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))

    op.drop_table('jobs')
    op.drop_table('analysis_spectra')
    with op.batch_alter_table('spectra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spectra_spectrum_uuid'))
        batch_op.drop_index(batch_op.f('ix_spectra_name'))
        batch_op.drop_index(batch_op.f('ix_spectra_id'))
        batch_op.drop_index(batch_op.f('ix_spectra_file_path'))

    op.drop_table('spectra')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_name'))
        batch_op.drop_index(batch_op.f('ix_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_analysis_uuid'))

    op.drop_table('analyses')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_uuid'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_is_archived'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
