method = "Monte Carlo"
fitmethod = "leastsq"
requested_samples = 4
completed_samples = 4
workers = 4
parameters = ["__DW_AB_15N", "__KEX_AB", "__PB", "__R2_A_15N_500_0MHZ", "__R2_A_15N_800_0MHZ"]
samples_file = "samples.tsv"
summary_file = "summary.toml"
correlations_file = "correlations.tsv"
plots_file = "plots.pdf"
